[package]
name = "viaduct"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"
exclude = ["/android", "/ios"]

[lib]
crate-type = ["lib"]

[features]
default = []

[dependencies]
url = "2.2"
log = "0.4"
serde = "1"
serde_json = "1"
once_cell = "1.5"
thiserror = "1.0"
uniffi = "^0.15"
uniffi_macros = "^0.15"

[build-dependencies]
uniffi_build = { version = "^0.15", features = [ "builtin-bindgen" ]}